/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// UI View Type
export type ViewType = 'dashboard' | 'nova_sessao' | 'resumos' | 'teste_realizacao' | 'resultados' | 'historico' | 'perfil';

// Support Disciplines
export const DISCIPLINES = [
  "Algoritmos e Tipos Abstratos de Dados",
  "Complementos de Bases de Dados",
  "Computação Móvel",
  "Computação Paralela e Distribuída",
  "Desenvolvimento de Videojogos",
  "Interação Pessoa-Máquina",
  "Matemática Discreta",
  "Matemática I",
  "Métodos Estatísticos",
  "Programação Avançada",
  "Programação Orientada por Objetos",
  "Programação para a Web",
  "Sistemas Operativos"
];

// Part I - Escolha Múltipla Question
export interface ChoiceQuestion {
  id: string;
  question: string;
  options: {
    A: string;
    B: string;
    C: string;
    D: string;
  };
  correctAnswer: 'A' | 'B' | 'C' | 'D';
  explanation: string;
}

// Part II - Desenvolvimento Question
export interface EssayQuestion {
  id: string;
  question: string;
  modelAnswer: string;
  keyPoints: string[];
  maxScore: number;
}

// Part III - Código/Programação Question
export interface CodeQuestion {
  id: string;
  question: string;
  language: string;
  starterCode: string;
  modelAnswer: string;
  explanation: string;
  maxScore: number;
}

// Complete Questions Payload generated by Gemini
export interface TestQuestions {
  partI: ChoiceQuestion[];
  partII: EssayQuestion[];
  partIII: CodeQuestion[];
}

// Development Grade item
export interface EssayGradeItem {
  questionId: string;
  score: number;
  feedback: string;
  strengths: string[];
  improvements: string[];
}

// Code Grade item
export interface CodeGradeItem {
  questionId: string;
  score: number;
  feedback: string;
  isLogicCorrect: boolean;
  issues: string[];
}

// AI Correction Result
export interface AICorrectionResult {
  developmentGrades: EssayGradeItem[];
  codeGrades: CodeGradeItem[];
}

// Answers provided by user for a test
export interface TestAnswers {
  partI: Record<string, 'A' | 'B' | 'C' | 'D'>; // questionId -> selectedOption
  partII: Record<string, string>; // questionId -> answerText
  partIII: Record<string, string>; // questionId -> codeText
}

// Historical Test record stored in localStorage
export interface HistoricalTest {
  id: number;
  name: string;
  discipline: string;
  numeroTeste?: string;
  date: string; // ISO Date String
  score: number; // 0-20 score scale
  totalQuestions: number;
  partI: {
    correct: number;
    total: number;
  };
  partII: {
    score: number;
    total: number;
  };
  partIII: {
    score: number;
    total: number;
  };
  questions: TestQuestions;
  answers: TestAnswers;
  grades: AICorrectionResult;
}

// Summary item stored in localStorage
export interface SavedSummary {
  id: number;
  discipline: string;
  nomeTeste?: string;
  pdfName: string;
  date: string; // ISO Date String
  content: string; // Markdown summary generated by AI
}
